#!/bin/bash
#*******************************************************************************
# * Copyright [2022] [IBM]
# *
# * Licensed under the Apache License, Version 2.0 (the "License");
# * you may not use this file except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *     http://www.apache.org/licenses/LICENSE-2.0
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *******************************************************************************
if [ `whoami` != root ]; then
    echo Please run this script as root or using sudo
    exit
fi
#
# NVIDIA driver should be installed on host OS
#

## https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/10.2/ubuntu18.04-x86_64/base/Dockerfile
sudo apt-get update && \
sudo apt-get install -y --no-install-recommends gnupg2 curl ca-certificates wget && \
sudo rm -rf /var/lib/apt/lists/* && \
sudo wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb && \
sudo dpkg -i cuda-keyring_1.0-1_all.deb

export CUDA_VERSION="10.2.89"
export CUDA_PKG_VERSION="10-2=$CUDA_VERSION-1"

# For libraries in the cuda-compat-* package: https://docs.nvidia.com/cuda/eula/index.html#attachment-a
sudo apt-get update && \
sudo apt-get install -y --no-install-recommends cuda-cudart-$CUDA_PKG_VERSION cuda-compat-10-2 && \
sudo ln -s cuda-10.2 /usr/local/cuda && \
sudo rm -rf /var/lib/apt/lists/*

# Required for nvidia-docker v1
echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf && \
echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf

export PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:${PATH}
export LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64

## https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/10.2/ubuntu18.04-x86_64/runtime/Dockerfile
export NCCL_VERSION=2.9.6

sudo apt-get update && \
sudo apt-get install -y --no-install-recommends cuda-libraries-$CUDA_PKG_VERSION \
                                           cuda-npp-$CUDA_PKG_VERSION \
					   cuda-nvtx-$CUDA_PKG_VERSION \
					   libcublas10=10.2.2.89-1 \
					   libnccl2=$NCCL_VERSION-1+cuda10.2 && \
sudo apt-mark hold libnccl2 && \
sudo rm -rf /var/lib/apt/lists/*

## https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/10.2/ubuntu18.04-x86_64/runtime/cudnn7/Dockerfile
export CUDNN_VERSION="7.6.5.32"

# LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

sudo apt-get update && \
sudo apt-get install -y --no-install-recommends libcudnn7=$CUDNN_VERSION-1+cuda10.2 && \
sudo apt-mark hold libcudnn7 && \
sudo rm -rf /var/lib/apt/lists/*

